# Generated by Django 6.1 on 2026-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('HIM', 'Health Information Manager'), ('NURSE', 'Nurse'), ('MLS', 'Medical Laboratory Scientist'), ('OPTOMETRIST', 'Optometrist'), ('PHYSICIAN', 'Physician'), ('PHARMACY', 'Pharmacy')], max_length=20),
        ),
    ]
