# Generated by Django 6.1 on 2026-08-20 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0002_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyorder',
            name='dispensed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_pharmacy_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('ANTIBIOTICS', 'Antibiotics'), ('ANALGESICS', 'Analgesics'), ('ANTIHYPERTENSIVE', 'Antihypertensive'), ('ANTIDIABETIC', 'Antidiabetic'), ('ANTIMALARIAL', 'Antimalarial'), ('ANTIVIRAL', 'Antiviral'), ('ANTIFUNGAL', 'Antifungal'), ('CARDIOVASCULAR', 'Cardiovascular'), ('RESPIRATORY', 'Respiratory'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('NEUROLOGICAL', 'Neurological'), ('VITAMINS', 'Vitamins & Supplements'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('dosage_form', models.CharField(blank=True, help_text='e.g., Tablet, Capsule, Syrup', max_length=100)),
                ('strength', models.CharField(blank=True, help_text='e.g., 500mg, 10mg/ml', max_length=50)),
                ('quantity', models.IntegerField(default=0, help_text='Available stock quantity')),
                ('reorder_level', models.IntegerField(default=10, help_text='Alert when stock reaches this level')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='b_drug_name_5968d0_idx'), models.Index(fields=['category'], name='b_drug_categor_86ce0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PharmacyDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_dispensed', models.IntegerField()),
                ('dispensing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_drugs', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='b.drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_medications', to='b.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='b.pharmacyorder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
