# Generated by Django 6.1 on 2026-08-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0003_alter_pharmacyorder_dispensed_by_drug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorytest',
            name='hcv',
        ),
        migrations.RemoveField(
            model_name='laboratorytest',
            name='hiv',
        ),
    ]
