# Generated by Django 6.1 on 2026-08-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_remove_laboratorytest_hcv_remove_laboratorytest_hiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingassessment',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True),
        ),
        migrations.AlterField(
            model_name='nursingassessment',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True),
        ),
        migrations.AlterField(
            model_name='nursingassessment',
            name='pulse_rate',
            field=models.IntegerField(blank=True, help_text='Pulse rate (beats/min)', null=True),
        ),
    ]
