# Generated by Django 6.1 on 2026-08-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0005_alter_nursingassessment_blood_pressure_diastolic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='dosage_form',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='generic_name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.CharField(choices=[('ANTIBIOTICS', 'Antibiotics'), ('ANALGESICS', 'Analgesics'), ('ANTIHYPERTENSIVE', 'Antihypertensive'), ('ANTIDIABETIC', 'Antidiabetic'), ('ANTIMALARIAL', 'Antimalarial'), ('ANTIVIRAL', 'Antiviral'), ('ANTIFUNGAL', 'Antifungal'), ('CARDIOVASCULAR', 'Cardiovascular'), ('RESPIRATORY', 'Respiratory'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('NEUROLOGICAL', 'Neurological'), ('VITAMINS', 'Vitamins & Supplements'), ('DERMATOLOGICAL', 'Dermatological'), ('OPHTHALMIC', 'Ophthalmic'), ('INJECTABLES', 'Injectables'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(help_text='e.g., Ibuprofen 200mg, Paracetamol 500mg, Amlodipine 10mg', max_length=200),
        ),
    ]
