# Generated by Django 6.1 on 2026-08-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0006_remove_drug_batch_number_remove_drug_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacydispensing',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_records', to='b.drug'),
        ),
    ]
