# Generated by Django 6.1 on 2026-08-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0007_alter_pharmacydispensing_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorytest',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='viewed_by_physician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opticalassessment',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opticalassessment',
            name='viewed_by_physician',
            field=models.BooleanField(default=False),
        ),
    ]
