# Generated by Django 6.1 on 2026-08-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0008_laboratorytest_viewed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opticalassessment',
            name='viewed_by_physician',
        ),
        migrations.AddField(
            model_name='opticalassessment',
            name='viewed_by_optician',
            field=models.BooleanField(default=False),
        ),
    ]
