# Generated by Django 6.1 on 2026-08-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0009_remove_opticalassessment_viewed_by_physician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalassessment',
            name='viewed_by_physician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opticalassessment',
            name='viewed_by_physician_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
